name: Go Install Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            ca-certificates chromium chromium-driver jq curl

      - name: Get OS and arch info
        id: vars
        run: |
          VER=$(curl -s https://api.github.com/repos/helviojunior/sprayshark/releases/latest | jq -r '.tag_name' | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
          GITHASH=$(git rev-parse --short HEAD)
          BUILDENV=$(go version | cut -d' ' -f 3,4 | sed 's/ /_/g')
          BUILDTIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          LDFLAGS="-s -w \
            -X=github.com/helviojunior/sprayshark/internal/version.Version=$VER \
            -X=github.com/helviojunior/sprayshark/internal/version.GitHash=$GITHASH \
            -X=github.com/helviojunior/sprayshark/internal/version.GoBuildEnv=$BUILDENV \
            -X=github.com/helviojunior/sprayshark/internal/version.GoBuildTime=$BUILDTIME"

          echo "LDFLAGS=$LDFLAGS" >> $GITHUB_OUTPUT

      - name: Install sprayshark at specific commit
        run: |
          sudo apt-get update && sudo apt-get install -y \
            ca-certificates chromium chromium-driver
          go install github.com/helviojunior/sprayshark@${GITHUB_SHA} -ldflags="${{ steps.vars.outputs.LDFLAGS }}"

      - name: Verify Installation
        run: |
          sprayshark spray -h
          sprayshark version
