on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get OS and arch info
        id: vars
        run: |
          VER=$(echo '${{ github.event.release.tag_name }}' | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
          GITHASH=$(git rev-parse --short HEAD)
          BUILDENV=$(go version | cut -d' ' -f 3,4 | sed 's/ /_/g')
          BUILDTIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

          echo "VER=$VER" >> $GITHUB_OUTPUT
          echo "GITHASH=$GITHASH" >> $GITHUB_OUTPUT
          echo "BUILDENV=$BUILDENV" >> $GITHUB_OUTPUT
          echo "BUILDTIME=$BUILDTIME" >> $GITHUB_OUTPUT

      - uses: wangyoucao577/go-release-action@v1.33
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.23.5.linux-amd64.tar.gz"
          ldflags: |
            -s -w \
            -X=github.com/helviojunior/sprayshark/internal/version.Version=${{ steps.vars.outputs.VER }} \
            -X=github.com/helviojunior/sprayshark/internal/version.GitHash=${{ steps.vars.outputs.GITHASH }} \
            -X=github.com/helviojunior/sprayshark/internal/version.GoBuildEnv=${{ steps.vars.outputs.BUILDENV }} \
            -X=github.com/helviojunior/sprayshark/internal/version.GoBuildTime=${{ steps.vars.outputs.BUILDTIME }}

